spring:
 datasource:
  url: jdbc:h2:file:/tmp/testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
 h2.console.enabled: true
 mvc:
   date-format: yyyy/MM/dd
   hiddenmethod.filter.enabled: true
 server:
  servlet:
    session:
      timeout=20

lesson2:
 string:
  property: Some text
  propertyDefault:
 int:
  prooperty:
 boolean:
  property: false
